export interface IStudents {
    userId: String,
    lrn: String,
    statusOfApplicant: String,
    schoolName: String,
    dateOfBirth: Date,
    age: Number,
    gender: String,
    civilStatus: String,
    phoneNumber: String,
    email: String,
    mothersName: String,
    mothersOccupation: String,
    fathersName: String,
    fathersOccupation: String,
    guardiansName: String,
    guardiansMobileNumber: String,
    houseNumber: String,
    street: String,
    barangay: String,
    municipality: String,
    province: String,
    zipCode: Number,
}